### ISSUE TITLE
4004 CPU

### ISSUE THREAD

**Issue by triesen** [jim11662418/4004-SBC#1]
Hi Jim
I tried to get in contact with you since a few weeks. According to your schematic I made a pcb, and it works well. Are you interested in this pcb?

I am missing the 4004reg.inc file for the AS compiler? Without this file it's not possible to compile the software. Is it possible to add this file in your repository?

![4004_SBC_rt01](https://user-images.githubusercontent.com/12643882/107225055-9c5c8300-6a18-11eb-91a3-99a2aa548cae.jpg)

Thank you for sharing your project!
Thomas

**Comment by jim11662418** [comment]
reg4004.inc added to repository. Sorry for not including it originally.
